image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      pip install tensorflow==2.16.1 pillow numpy tensorflowjs==4.19.0
      echo "Installed Python packages!"

  - command: |
      echo "Ready to code!"
