image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      pip install tensorflow==2.8.0 pillow numpy tensorflowjs==3.15.0
      echo "Installed Python packages!"

  - command: |
      echo "Ready to code!"
