image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      pip install tensorflow==2.6.2 pillow numpy==1.19.5  tensorflowjs==3.18.0
      echo "Installed Python packages!"

  - command: |
      echo "Ready to code!"
