image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      pip install tensorflow==2.15.0 pillow numpy tensorflowjs
      echo "Installed Python packages!"

  - command: |
      echo "Ready to code!"
